version: "3"

services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5433:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=agustinus@indomaret.co.id
      - PGADMIN_DEFAULT_PASSWORD=postgres